#include "mediageometry.h"
#include "deckgeometry.h"
#include <QTest>
#include <QPointer>
#include <QFile>
#include <QDir>
#include <QQmlComponent>
#include <QQmlEngine>
#include <memory>
#include <type_traits>
#include <cmath>
#include <map>
#include <array>

class GeometryTest : public QObject {
    Q_OBJECT
private slots:
    void qmlInitializationRetainsFinalPropertiesAndLiveUpdates() {
        // Batching initial QML assignments must produce the same data as the
        // C++ setters, and must not suppress changes after componentComplete.
        const auto verify=[&]<typename T>(const char *name,const QByteArray &declaration,
                                         const QVariantMap &initial,const char *property,const QVariant &next) {
            qmlRegisterType<T>("GeometryLifecycle",1,0,name);
            QQmlEngine engine;
            QQmlComponent component(&engine);
            component.setData("import QtQuick\nimport GeometryLifecycle 1.0\n"+QByteArray(name)+" { "+declaration+" }",QUrl());
            QTRY_VERIFY_WITH_TIMEOUT(component.status()!=QQmlComponent::Loading,3000);
            QVERIFY2(component.isReady(),qPrintable(component.errorString()));
            std::unique_ptr<QObject> object(component.create());
            auto *qml=qobject_cast<T*>(object.get());QVERIFY(qml);
            T native;
            for(auto it=initial.cbegin();it!=initial.cend();++it)QVERIFY(native.setProperty(it.key().toLatin1(),it.value()));
            const auto bytes=[](T *item) {
                if constexpr(std::is_base_of_v<QQuick3DGeometry,T>)return item->vertexData();
                else return item->textureData();
            };
            QCOMPARE(bytes(qml),bytes(&native));
            const auto before=bytes(qml);
            QVERIFY(qml->setProperty(property,next));QVERIFY(native.setProperty(property,next));
            QCOMPARE(bytes(qml),bytes(&native));QVERIFY(bytes(qml)!=before);
        };
        verify.operator()<DeckGeometry>("DeckGeometry","dimensions: Qt.vector3d(12, 21, 11); radius: 3",
            {{"dimensions",QVector3D(12,21,11)},{"radius",3.f}},"radius",2.f);
        verify.operator()<RecordGeometry>("RecordGeometry","radius: 40; hole: 4; depth: 3; grooves: true",
            {{"radius",40.f},{"hole",4.f},{"depth",3.f},{"grooves",true}},"radius",36.f);
        verify.operator()<WaveGeometry>("WaveGeometry","progress: 0.6; phase: 1.7; amplitude: 2.4; linear: true",
            {{"progress",.6f},{"phase",1.7f},{"amplitude",2.4f},{"linear",true}},"phase",2.f);
        verify.operator()<TurntableDetailGeometry>("TurntableDetailGeometry","fascia: true",{{"fascia",true}},"fascia",false);
        verify.operator()<SurfaceTexture>("SurfaceTexture","kind: \"vinyl-normal\"",{{"kind","vinyl-normal"}},"kind","bead-normal");
        verify.operator()<StudioTexture>("StudioTexture","tint: \"#80b8e8\"; ambientLift: 0.3",
            {{"tint",QColor("#80b8e8")},{"ambientLift",.3f}},"tint",QColor("#e8ac80"));
        verify.operator()<CoverTexture>("CoverTexture","paper: true; title: \"Album\"; artist: \"Artist\"",
            {{"paper",true},{"title","Album"},{"artist","Artist"}},"title","Changed album");
    }
    void exportCompatibilitySamples() {
        const auto path=qEnvironmentVariable("SPUN_GEOMETRY_SNAPSHOTS");
        if(path.isEmpty())QSKIP("Set SPUN_GEOMETRY_SNAPSHOTS to compare generated bytes across builds");
        QDir().mkpath(path);
        const auto save=[&](const QString &name,const QByteArray &bytes) {
            QFile file(path+"/"+name);QVERIFY(file.open(QIODevice::WriteOnly));QCOMPARE(file.write(bytes),bytes.size());
        };
        for(const QString kind:{"brushed","molded","vinyl","disc","turned","metal-normal","paper","knurled-normal","bead-normal","vinyl-normal","lacquer","powder","satin","leather-normal","turned-normal"}) {
            SurfaceTexture texture;texture.setProperty("kind",kind);save("texture-"+kind,texture.textureData());
        }
        int i=0;
        for(const QColor tint:{QColor(Qt::white),QColor("#80b8e8"),QColor("#e8ac80")})for(float lift:{0.f,.3f}) {
            StudioTexture texture;texture.setProperty("tint",tint);texture.setProperty("ambientLift",lift);save("studio-"+QString::number(i++),texture.textureData());
        }
        i=0;
        for(const auto dimensions:{QVector3D(4,.7,.3),QVector3D(428,428,28),QVector3D(12,21,11),QVector3D(535,398,42)})for(float radius:{.1f,2.f,22.f}) {
            DeckGeometry mesh;mesh.setProperty("dimensions",dimensions);mesh.setProperty("radius",radius);save("deck-"+QString::number(i++),mesh.vertexData());
        }
        i=0;
        for(float radius:{3.2f,26.f,40.f,176.f})for(float depth:{.05f,2.f,12.f})for(bool grooves:{false,true}) {
            RecordGeometry mesh;mesh.setProperty("radius",radius);mesh.setProperty("depth",depth);mesh.setProperty("grooves",grooves);save("record-"+QString::number(i++),mesh.vertexData());
        }
        i=0;
        for(bool linear:{false,true})for(float progress:{0.f,.25f,1.f})for(float phase:{0.f,1.7f}) {
            WaveGeometry mesh;mesh.setProperty("linear",linear);mesh.setProperty("progress",progress);mesh.setProperty("phase",phase);mesh.setProperty("amplitude",2.4f);save("wave-"+QString::number(i++),mesh.vertexData());
        }
    }
    void cassetteCarrierHasOpeningsAndClosedEdges() {
        CassettePlateGeometry mesh;
        const auto data=mesh.vertexData();QVERIFY(!data.isEmpty());QVERIFY(data.size()<60000);
        const auto *v=reinterpret_cast<const float*>(data.constData());
        std::map<std::array<float,6>,int> edges;
        for(int i=0;i<data.size()/int(sizeof(float));i+=24) {
            std::array<std::array<float,3>,3> points;
            for(int k=0;k<3;++k) {
                const int n=i+k*8;
                for(int j=0;j<8;++j)QVERIFY(std::isfinite(v[n+j]));
                QVERIFY(std::abs(QVector3D(v[n+3],v[n+4],v[n+5]).length()-1)<.001);
                points[k]={v[n],v[n+1],v[n+2]};
            }
            for(int k=0;k<3;++k) {
                auto a=points[k],b=points[(k+1)%3];if(b<a)std::swap(a,b);
                ++edges[{a[0],a[1],a[2],b[0],b[1],b[2]}];
            }
            const float cx=(v[i]+v[i+8]+v[i+16])/3,cy=(v[i+1]+v[i+9]+v[i+17])/3;
            if(std::abs(v[i+5])>.99) {
                QVERIFY(!(cx>-109&&cx<-76&&cy>-7&&cy<36));
                QVERIFY(!(cx>35&&cx<60&&cy>-31&&cy<36));
            }
        }
        for(const auto &[edge,count]:edges){Q_UNUSED(edge);QCOMPARE(count,2);}
        QCOMPARE(mesh.boundsMax().z()-mesh.boundsMin().z(),3.f);
    }
    void cassetteGearHasThicknessAndOpenShaft() {
        CassetteGearGeometry gear;
        const auto data=gear.vertexData();QVERIFY(!data.isEmpty());QVERIFY(data.size()<100000);
        const auto *v=reinterpret_cast<const float*>(data.constData());
        float low=100,high=-100;
        for(int i=0;i<data.size()/int(sizeof(float));i+=24) {
            for(int k=0;k<24;++k)QVERIFY(std::isfinite(v[i+k]));
            const QVector3D a(v[i],v[i+1],v[i+2]),b(v[i+8],v[i+9],v[i+10]),c(v[i+16],v[i+17],v[i+18]);
            QVERIFY(QVector3D::crossProduct(b-a,c-a).lengthSquared()>1e-10f);
            for(int k=0;k<24;k+=8) {
                QVERIFY(std::hypot(v[i+k],v[i+k+1])>=2.99f);
                QVERIFY(std::hypot(v[i+k],v[i+k+1])<=20.01f);
                QVERIFY(std::abs(QVector3D(v[i+k+3],v[i+k+4],v[i+k+5]).length()-1)<.001);
                low=qMin(low,v[i+k+2]);high=qMax(high,v[i+k+2]);
            }
            const float area=(v[i+14]-v[i+6])*(v[i+23]-v[i+7])-(v[i+15]-v[i+7])*(v[i+22]-v[i+6]);
            QVERIFY(std::abs(area)>1e-9f);
        }
        QCOMPARE(high-low,4.f);
    }
    void turntableDetails() {
        for(bool fascia:{false,true}) {
            TurntableDetailGeometry mesh;mesh.setProperty("fascia",fascia);
            const auto data=mesh.vertexData();QVERIFY(!data.isEmpty());QVERIFY(data.size()<300000);
            const auto *v=reinterpret_cast<const float*>(data.constData());
            for(int i=0;i<data.size()/int(sizeof(float));i+=8) {
                for(int k=0;k<8;++k)QVERIFY(std::isfinite(v[i+k]));
                QVERIFY(std::abs(QVector3D(v[i+3],v[i+4],v[i+5]).length()-1)<.001);
                QVERIFY(v[i+2]>=mesh.boundsMin().z()-.001f&&v[i+2]<=mesh.boundsMax().z()+.001f);
                if(!fascia)for(int row=-1;row<=1;++row)for(int col=-1;col<=1;++col)
                    QVERIFY(std::hypot(v[i]-col*6,v[i+1]-row*6)>1.79);
            }
        }
    }
    void recordTopology_data() {
        QTest::addColumn<float>("hole");QTest::addColumn<bool>("grooves");
        QTest::newRow("CD")<<15.f<<false;QTest::newRow("vinyl")<<3.5f<<true;QTest::newRow("tape-pack")<<31.f<<false;
    }
    void recordTopology() {
        QFETCH(float,hole);QFETCH(bool,grooves);
        RecordGeometry record;record.setProperty("hole",hole);record.setProperty("grooves",grooves);
        const auto data=record.vertexData();QVERIFY(!data.isEmpty());QCOMPARE(data.size()%(3*record.stride()),0);
        const float *values=reinterpret_cast<const float*>(data.constData());const int stride=record.stride()/sizeof(float);
        float minZ=100,maxZ=-100;
        for(int i=0;i<data.size()/int(sizeof(float));i+=stride){
            for(int j=0;j<stride;++j)QVERIFY(std::isfinite(values[i+j]));
            const float x=values[i],y=values[i+1],z=values[i+2];
            QVERIFY(std::hypot(x,y)>=hole-.01);QVERIFY(std::hypot(x,y)<=176.01);
            const auto n=QVector3D(values[i+3],values[i+4],values[i+5]);QVERIFY(std::abs(n.length()-1)<.001);
            QVERIFY(values[i+6]>=0&&values[i+6]<=1);QVERIFY(values[i+7]>=0&&values[i+7]<=1);
            minZ=qMin(minZ,z);maxZ=qMax(maxZ,z);
        }
        QVERIFY(minZ<0&&maxZ>0);QVERIFY(record.boundsMin().z()<=minZ);QVERIFY(record.boundsMax().z()>=maxZ);
    }
    void cartridgeProportions() {
        DeckGeometry body;body.setProperty("dimensions",QVector3D(12,21,11));body.setProperty("radius",3.f);
        QCOMPARE(body.boundsMax()-body.boundsMin(),QVector3D(12,21,11));
        QVERIFY(body.vertexData().size()>0);
    }
    void narrowRingsRetainValidChamfers() {
        for(float thickness:{.05f,.25f,3.5f}) {
            RecordGeometry ring;ring.setProperty("radius",3.2f);ring.setProperty("hole",3.f);ring.setProperty("depth",thickness);
            const auto bytes=ring.vertexData();const auto *v=reinterpret_cast<const float*>(bytes.constData());
            bool hasChamfer=false;
            for(int i=0;i<bytes.size()/int(sizeof(float));i+=24) {
                const QVector3D a(v[i],v[i+1],v[i+2]),b(v[i+8],v[i+9],v[i+10]),c(v[i+16],v[i+17],v[i+18]);
                QVERIFY(QVector3D::crossProduct(b-a,c-a).lengthSquared()>1e-14f);
                for(int k=0;k<24;k+=8) {
                    const float radius=std::hypot(v[i+k],v[i+k+1]);
                    QVERIFY(radius>=2.999f&&radius<=3.201f);
                    QVERIFY(std::abs(v[i+k+2])<=thickness/2+.001f);
                    const QVector3D normal(v[i+k+3],v[i+k+4],v[i+k+5]);
                    QVERIFY(std::abs(normal.length()-1)<.001f);
                    hasChamfer=hasChamfer||(normal.z()>.1f&&normal.z()<.99f);
                }
            }
            QVERIFY(hasChamfer);
        }
    }
    void reelHasOpenShaftAndThreeThroughWindows() {
        ReelGeometry reel;const auto bytes=reel.vertexData();const auto *v=reinterpret_cast<const float*>(bytes.constData());
        const auto covered=[&](QVector2D p) {
            for(int i=0;i<bytes.size()/int(sizeof(float));i+=24) {
                if(v[i+5]<.9f)continue;
                const QVector2D a(v[i],v[i+1]),b(v[i+8],v[i+9]),c(v[i+16],v[i+17]);
                const auto cross=[](QVector2D a,QVector2D b){return a.x()*b.y()-a.y()*b.x();};
                if(cross(b-a,p-a)>=0&&cross(c-b,p-b)>=0&&cross(a-c,p-c)>=0)return true;
            }
            return false;
        };
        QVERIFY(!covered({0,0}));
        for(int i=0;i<3;++i) {
            const float angle=i*2*float(M_PI)/3;
            QVERIFY(!covered({20*std::cos(angle),20*std::sin(angle)}));
            QVERIFY(covered({20*std::cos(angle+float(M_PI)/3),20*std::sin(angle+float(M_PI)/3)}));
        }
        using Point=std::array<int,3>;using Edge=std::array<Point,2>;
        std::map<Edge,int> edges;
        for(int i=0;i<bytes.size()/int(sizeof(float));i+=24) {
            std::array<Point,3> points;
            for(int k=0;k<3;++k) {
                for(int axis=0;axis<3;++axis) {
                    const float value=v[i+k*8+axis];QVERIFY(std::isfinite(value));
                    QVERIFY(value>=reel.boundsMin()[axis]-.001f&&value<=reel.boundsMax()[axis]+.001f);
                    points[k][axis]=qRound(value*1000);
                }
                QVERIFY(std::abs(QVector3D(v[i+k*8+3],v[i+k*8+4],v[i+k*8+5]).length()-1)<.001f);
            }
            for(int k=0;k<3;++k){Edge edge={points[k],points[(k+1)%3]};if(edge[1]<edge[0])std::swap(edge[0],edge[1]);++edges[edge];}
        }
        for(const auto &[edge,count]:edges){Q_UNUSED(edge);QCOMPARE(count,2);}
    }
    void thinMachinedPartsStayInsideBounds() {
        for(const auto size:{QVector3D(4,.7,.3),QVector3D(428,428,28),QVector3D(12,21,11)}){
            DeckGeometry body;body.setProperty("dimensions",size);body.setProperty("radius",2.f);
            const auto bytes=body.vertexData();const auto *v=reinterpret_cast<const float*>(bytes.constData());
            for(int i=0;i<bytes.size()/int(sizeof(float));i+=8){
                for(int axis=0;axis<3;++axis)QVERIFY(std::abs(v[i+axis])<=size[axis]/2+.001f);
                QVERIFY(std::abs(QVector3D(v[i+3],v[i+4],v[i+5]).length()-1)<.001f);
            }
        }
    }
    void texturedHardwareHasNoCollapsedUvTriangles() {
        DeckGeometry deck;deck.setProperty("dimensions",QVector3D(535,398,42));deck.setProperty("radius",3.f);
        TurntableDetailGeometry headshell,fascia;fascia.setProperty("fascia",true);
        for(auto *geometry:QList<QQuick3DGeometry*>{&deck,&headshell,&fascia}) {
            const auto bytes=geometry->vertexData();const auto *v=reinterpret_cast<const float*>(bytes.constData());
            for(int i=0;i<bytes.size()/int(sizeof(float));i+=24) {
                const double du1=v[i+14]-v[i+6],dv1=v[i+15]-v[i+7],du2=v[i+22]-v[i+6],dv2=v[i+23]-v[i+7];
                QVERIFY2(std::abs(du1*dv2-du2*dv1)>1e-12,"Normal mapped triangles must have a finite tangent basis");
            }
        }
    }
    void cylindricalWallsHaveAxialTextureCoordinates() {
        RecordGeometry ring;ring.setProperty("depth",12.f);ring.setProperty("radius",40.f);
        const auto bytes=ring.vertexData();const auto *v=reinterpret_cast<const float*>(bytes.constData());
        int sides=0;
        for(int i=0;i<bytes.size()/int(sizeof(float));i+=24) {
            if(std::abs(v[i+5])>.1f)continue;
            ++sides;
            const float low=qMin(v[i+7],qMin(v[i+15],v[i+23])),high=qMax(v[i+7],qMax(v[i+15],v[i+23]));
            QVERIFY(high-low>.9f);
            const float uLow=qMin(v[i+6],qMin(v[i+14],v[i+22])),uHigh=qMax(v[i+6],qMax(v[i+14],v[i+22]));
            QVERIFY(uHigh-uLow<.1f);
        }
        QVERIFY(sides>40);
    }
    void materialMapsAreBoundedAndRepeatable() {
        QByteArray previous;
        for(const QString kind:{QString("brushed"),QString("molded"),QString("vinyl"),QString("disc"),QString("turned"),QString("metal-normal"),QString("paper"),QString("knurled-normal"),QString("bead-normal"),QString("vinyl-normal"),QString("lacquer"),QString("powder"),QString("satin"),QString("leather-normal"),QString("turned-normal")}){
            SurfaceTexture first,second;first.setProperty("kind",kind);second.setProperty("kind",kind);
            const int size=(kind=="vinyl-normal"||kind=="lacquer")?1024:kind=="powder"?512:256;
            QCOMPARE(first.size(),QSize(size,size));QCOMPARE(first.textureData().size(),size*size*4);
            QCOMPARE(first.textureData(),second.textureData());QVERIFY(first.textureData()!=previous);
            previous=first.textureData();
        }
    }
    void fineFinishesHaveFiniteNormalsAndNoTileSeams() {
        for(const QString &kind:{QString("leather-normal"),QString("turned-normal"),QString("knurled-normal")}) {
            SurfaceTexture texture;texture.setProperty("kind",kind);
            const auto data=texture.textureData();const auto *p=reinterpret_cast<const unsigned char*>(data.constData());
            for(int i=0;i<256*256;++i) {
                const QVector3D normal(p[i*4]/127.5f-1,p[i*4+1]/127.5f-1,p[i*4+2]/127.5f-1);
                QVERIFY(std::abs(normal.length()-1)<.012f);QVERIFY(normal.z()>.9f);
                QCOMPARE(p[i*4+3],255);
            }
            if(kind=="leather-normal")for(int i=0;i<256;++i)for(int c=0;c<3;++c) {
                QVERIFY(std::abs(int(p[(i*256)*4+c])-int(p[(i*256+255)*4+c]))<24);
                QVERIFY(std::abs(int(p[i*4+c])-int(p[((255*256)+i)*4+c]))<24);
            }
        }
    }
    void coversUseBoundedIndependentPixels() {
        CoverTexture cover;QImage input(1200,600,QImage::Format_RGBA8888);input.fill(Qt::red);cover.setProperty("artwork",input);
        QCOMPARE(cover.size(),QSize(512,512));QCOMPARE(cover.textureData().size(),512*512*4);
        input.fill(Qt::blue);QCOMPARE(static_cast<unsigned char>(cover.textureData()[0]),255);
        cover.setProperty("artwork",input);QCOMPARE(static_cast<unsigned char>(cover.textureData()[2]),255);
        cover.setProperty("artwork",QImage());QCOMPARE(cover.textureData().size(),512*512*4);
    }
    void coverSnapshotsReplaceAndRetireTextures() {
        CoverTexture cover;QImage image(64,64,QImage::Format_RGBA8888);image.fill(Qt::red);
        cover.setProperty("artwork",image);
        QPointer<QQuick3DTextureData> previous=cover.texture();
        const auto pixels=previous->textureData();
        image.fill(Qt::blue);cover.setProperty("artwork",image);
        QVERIFY(cover.texture()!=previous);QCOMPARE(previous->textureData(),pixels);
        QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);
        QVERIFY(previous.isNull());
        const auto *unchanged=cover.texture();
        cover.setProperty("artwork",image.copy());QCOMPARE(cover.texture(),unchanged);
        for(int i=0;i<30;++i){image.fill(i%2?Qt::red:Qt::blue);cover.setProperty("artwork",image);}
        QCoreApplication::sendPostedEvents(nullptr,QEvent::DeferredDelete);
        QCOMPARE(cover.findChildren<QQuick3DTextureData*>().size(),1);
        QCOMPARE(cover.textureData().size(),512*512*4);
    }
    void paperLabelsAndWallpaperProbe() {
        CoverTexture label;label.setProperty("paper",true);label.setProperty("title",QString("Test album"));
        QCOMPARE(label.size(),QSize(1024,170));QCOMPARE(label.textureData().size(),1024*170*4);
        StudioTexture probe;const auto neutral=probe.textureData();probe.setProperty("tint",QColor("#80b8e8"));
        QCOMPARE(probe.size(),QSize(512,256));QCOMPARE(probe.textureData().size(),512*256*4);QVERIFY(probe.textureData()!=neutral);
        const auto blue=probe.textureData();probe.setProperty("tint",QColor("#e8ac80"));QVERIFY(probe.textureData()!=blue);
    }
    void studioProbeRetainsHdrAndSeamlessEdges() {
        StudioTexture probe;QCOMPARE(probe.format(),QQuick3DTextureData::RGBE8);
        const auto bytes=probe.textureData();const auto *p=reinterpret_cast<const unsigned char*>(bytes.constData());
        double minimum=10,maximum=0;
        const auto component=[&](int pixel,int channel){return std::ldexp(double(p[pixel*4+channel])/256,int(p[pixel*4+3])-128);};
        for(int i=0;i<512*256;++i)for(int channel=0;channel<3;++channel) {
            const double value=component(i,channel);QVERIFY(std::isfinite(value)&&value>=0&&value<4);
            minimum=qMin(minimum,value);maximum=qMax(maximum,value);
        }
        QVERIFY(maximum>2);QVERIFY(minimum<.1);
        for(int y=0;y<256;++y)for(int channel=0;channel<3;++channel)
            QVERIFY(std::abs(component(y*512,channel)-component(y*512+511,channel))<.015);
    }
    void waveIsFiniteAtEndpoints() {
        for(bool linear:{false,true})for(float progress:{0.f,.25f,1.f}){
            WaveGeometry wave;wave.setProperty("linear",linear);wave.setProperty("progress",progress);wave.setProperty("amplitude",2.4f);
            const auto bytes=wave.vertexData();const auto *values=reinterpret_cast<const float*>(bytes.constData());for(int i=0;i<bytes.size()/int(sizeof(float));++i)QVERIFY(std::isfinite(values[i]));
        }
    }
};
QTEST_MAIN(GeometryTest)
#include "geometrytest.moc"
